# Site settings
title: eileen.codes
name: Eileen M. Uchitelle
description: > # this means to ignore newlines until "baseurl:"
  <h3>About</h3>
  <p>Hi, I'm Eileen! I'm a programmer at <a href='http://basecamp.com' target='_blank'>Basecamp</a> (formerly 37signals) on the Security and Performance team. I'm an avid contributor to Open Source and am on the Rails Committers Team and the Rails Security Team. I enjoy <a href='/speaking'>speaking</a> at conferences, usually about performance or contributing to Open Source. Outside code, I enjoy craft beer and hiking with my husband, <a href='http://twitter.com/abeuchitelle' target='_blank'>Abe</a> and our dog, <a href='http://twitter.com/aryadog' target='_blank'>Arya</a>.</p>

url: "http://eileencodes.com" # the base hostname & protocol for your site
twitter_username: eileencodes
github_username:  eileencodes
linkedin_username: eileencodes

# Build settings
markdown: kramdown
permalink: "/posts/:title/"
paginate: 10
paginate_path: "/posts/:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "speaking"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout

gems:
  - jekyll-sitemap
